apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: gcr.io/jkwng-images/keda-bullmq-consumer:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_QUEUE_HOST
          value: 10.28.0.3
        - name: REDIS_QUEUE_PORT
          value: "6379"
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "2Gi"