apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  namespace: consumer
  labels:
    deploymentName: consumer
spec:
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 10  # Optional. Default: 30 seconds
  cooldownPeriod:  2 # Optional. Default: 300 seconds
  scaleTargetRef:
    name: consumer
  triggers:
    - type: redis
      metadata:
        address: 10.28.0.3:6379
        listName: "{dataSchedule}:dataSchedule:wait"
        listLength: "1" # 1 outstanding job -> 1 pod, until max replica
      # authenticationRef:
      #   name: keda-trigger-auth-redis-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  redis_username: YWRtaW4=
  redis_password: YWRtaW4=
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-redis-secret
spec:
  secretTargetRef:
  - parameter: username
    name: db-secret
    key: redis_username
  - parameter: password
    name: db-secret
    key: redis_password