apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: consumer
build:
  artifacts:
    - image: bullmq-consumer
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: jkwng-gke-keda-bullmq
manifests:
  rawYaml:
    - consumer.yaml
deploy:
  kubectl: {}