apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: provider
build:
  artifacts:
    - image: bullmq-producer
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: jkwng-gke-keda-bullmq
manifests:
  rawYaml:
    - provider.yaml
deploy:
  kubectl: {}